#!/bin/bash

# Are we in Git repository?
if [[ -d .git ]]; then
  # configure variables with default values,
  # then override those values if in config file
  mainbranch=$(git rev-parse --abbrev-ref HEAD);
  reponame=$(basename $(git rev-parse --show-toplevel));
  upstream="upstream"
  devsuffix="temp"
  emoji=1
  addall=0
  commitforce=0
  pushforce=0
  branchinprefix=1
  prefix=""
  uppercaseprefix=1
  noprefix=0
  opencompare=1

  # not actually an author, more like a github username
  author=$(git config --get remote.origin.url)
  author=${author#*:}
  author=${author%%/*}

  # Check if there is fancom config file:
  if [[ -f .fancom ]]; then
    # execute config file
    source .fancom
  fi

  if [[ $addall == 1 ]]; then
    echo 'adding all...';
    #git add --all;
  fi

  if [[ $noprefix == 1 ]]; then
    # we don't need any prefix.
    # even if `prefix` var has any value `noprefix`
    # option has higher priority
    commitmsg="";

  elif [[ $prefix && $noprefix == 0 ]]; then
    # prefix variable is set, and noprefix is disabled,
    # we set custom prefix
    if [[ $branchinprefix == 0 ]]; then
      commitmsg=$(echo '['$(echo $prefix)']');
    else
      commitmsg=$(echo '['$(echo $prefix $mainbranch)']');
    fi
  else
    if [[ $branchinprefix == 0 ]]; then
      commitmsg=$(echo '['$(echo $reponame)']');
    else
      commitmsg=$(echo '['$(echo $reponame $mainbranch)']');
    fi
  fi

  if [[ $uppercaseprefix == 1 ]]; then
    commitmsg=$(echo $commitmsg | tr '[:lower:]' '[:upper:]');
  fi

  if [[ $emoji == 1 ]]; then
    # add random emoji icon from .emo file
    commitmsg=$(echo $commitmsg $(head -$((${RANDOM} % `wc -l < .emo` + 1)) .emo | tail -1));
  fi

  if [[ $1 ]]; then
    msg=$1;
    # we have commit message!
    if [[ $1 == "-d" ]]; then
      msg=$3;
      data=$2;
    fi
    commitmsg=$(echo $commitmsg $msg);

    echo $commitmsg;
    tempBranch=$(echo $mainbranch-$devsuffix);
  else
    echo "No commit message!"
  fi

else
  echo "ERROR: Not in git repository (.git not found!)";
fi
